spring :
  application:
    name: api-gateway
  cloud:
    gateway:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: posts-service
              uri: lb://POSTS-SERVICE
              predicates:
                - Path=/posts/**

            - id: connections-service
              uri: lb://CONNECTIONS-SERVICE
              predicates:
                - Path=/connections/**





server:
  port: 9020
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




